### PR TITLE
Implement requestInterval middleware; close #30

### LINKED ISSUE #30: Support for self-throttling
We need a way to limit the rate at which API calls will be made. For example. I want to crawl the Family Tree, and I know my code will need to make a lot of API calls. I don't care as much how fast it takes. I just don't want to send a large burst of API calls to FamilySearch all at once.

When FamilySearch gets large sudden spikes or bursts of API traffic it causes server scale up events that can take up to 15 minutes for the servers to spin up. By that time the traffic could be over. So we incurred a cost to scale up our servers for no reason. If we can level out the API traffic bursts then the server scale up events can be minimized.

If we had a self-throttling lever of say an amount of time (1,000 milliseconds etc.) to wait before each API call is made, this would allow partner apps to "play nice" with our API and not send large bursts of requests.

### PR DESCRIPTION
**Pull request by justincy**
Possible implementation for #30. Is this what you were looking for?

### CODE REVIEW

**Comment by justincy** [comment]
@misbach Let me handle the merge, if you approve. I'd like to resolve the conflicts.

**Comment by misbach** [comment]
I like it! Go ahead and merge.

I'm curious... Is the requestInterval only read once at instantiation time? Or could you change it on the fly later on and have it take affect?

**Comment by justincy** [comment]
@misbach As implemented it's just read once. I _could_ allow it to be changed on the fly but I don't really want to. Do you imagine developers would want to change that value?

**Comment by misbach** [comment]
@justincy I was just curious. Leave it the way it is.

**Pull request merged**
